web_rm/smart_rm/urls.py
from django.conf.urls import url
from django.contrib import admin

from smart_rm import views

urlpatterns = [
    url(r'^view/(?P<path>.+)?', views.select_files_for_removing_view, name='view_files'),
    url(r'^remove/', views.remove_files, name='remove_files'),
    url(r'^add_bucket/', views.AddBucketView.as_view(), name='add_bucket'),
    url(r'^buckets/', views.view_buckets, name='view_buckets'),
    url(r'^del_bucket/(?P<pk>\d+)', views.BucketDelete.as_view(), name="del_bucket"),
    url(r'^bucket_files/(?P<pk>\d+)',views.view_bucket_contents, name="bucket_files" ),
    url(r'^restore_files/', views.restore_files, name="restore_files"),
    url(r'^clean_bucket/(?P<pk>\d+)',views.clean_bucket, name="clean_bucket"),
    url(r'^tasks/(?P<pk>\d+)', views.tasks_view, name="tasks"),
    url(r'^task_result/(?P<pk>\d+)', views.task_result_view, name="task_result" )
]

web_rm/web_rm/urls.py
from django.conf.urls import url, include
from django.contrib import admin

import smart_rm.urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include(smart_rm.urls, namespace='smart_rm'))
]

web_rm/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        {#        <link rel="stylesheet">#}
        <title>{% block title %}Home page{% endblock %} - WebRM</title>

        <script src="{% static "smart_rm/jquery.min.js"%}"></script>
        <link rel="stylesheet" href="{% static "smart_rm/bootstrap-3.3.7-dist/css/bootstrap.min.css" %}">
        <link rel="stylesheet" href="{% static "smart_rm/bootstrap-3.3.7-dist/css/bootstrap-theme.min.css" %}">
        <script src="{% static "smart_rm/bootstrap-3.3.7-dist/js/bootstrap.min.js" %}"></script>
        <link rel="stylesheet" href="{% static "styles.css" %}">

    </head>
    <body >
        <div class="fon_scroll">
            <div class="container" >
                <nav class="navbar navbar-inverse" role="navigation" >
                    <a class="navbar-brand" >WebRM</a>
                    <div class="collapse navbar-collapse">
                        <ul class="nav navbar-nav">
                            <li><a href="{% url "smart_rm:view_files" %}">Choose files for remove</a></li>
                            <li><a href="{% url "smart_rm:view_buckets" %}">Buckets</a></li>
                            <li><a href="{% url "smart_rm:add_bucket"%}">Add Bucket</a></li>
                        </ul>
                    </div>
                </nav>
            <div>
                {% block content %}

                {% endblock content %}
                <script type="text/javascript">
                <!--
                    $(function () {
                        $("#selall").click( function () {
                            $(".check_add").prop('checked', $("#selall").prop('checked') );
                        });
                    });

                    $(function () {
                        $("#size_checkbox").click( function () {
                            $("#size_input").prop('disabled', !$("#size_checkbox").prop('checked') );
                        });
                    });

                    $(function () {
                        $("#time_checkbox").click( function () {
                            $("#time_input").prop('disabled', !$("#time_checkbox").prop('checked') );
                        });
                    });
                //-->
                </script>
            </div>
            </div>
        </div>
    </body>
</html>