web_rm/smart_rm/urls.py
from django.conf.urls import url
from django.contrib import admin

from smart_rm import views

urlpatterns = [
    url(r'^view/(?P<path>.+)?', views.select_files_for_removing_view, name='view_files'),
    url(r'^remove/', views.remove_files, name='remove_files'),
    url(r'^add_bucket/', views.AddBucketView.as_view(), name='add_bucket'),
    url(r'^buckets/', views.view_buckets, name='view_buckets'),
    url(r'^del_bucket/(?P<pk>\d+)', views.BucketDelete.as_view(), name="del_bucket"),
    url(r'^bucket_files/(?P<pk>\d+)',views.view_bucket_contents, name="bucket_files" ),
    url(r'^restore_files/', views.restore_files, name="restore_files"),
    url(r'^clean_bucket/(?P<pk>\d+)',views.clean_bucket, name="clean_bucket"),
    url(r'^tasks/(?P<pk>\d+)', views.tasks_view, name="tasks"),
    url(r'^task_result/(?P<pk>\d+)', views.task_result_view, name="task_result" )
]

web_rm/web_rm/urls.py
from django.conf.urls import url, include
from django.contrib import admin

import smart_rm.urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include(smart_rm.urls, namespace='smart_rm'))
]

web_rm/smart_rm/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
from django.db import models


class BucketModel(models.Model):
    name = models.CharField(max_length=100, unique=True)
    bucket_path = models.CharField(max_length=1000, unique=True)
    files_path = models.CharField(max_length=1000, unique=True)
    info_path = models.CharField(max_length=1000, unique=True)
    history_path = models.CharField(max_length=1000, unique=True)
    max_size = models.PositiveIntegerField(default=1000000)
    time_files_storage = models.PositiveIntegerField(default=10)
    size_files_storage = models.PositiveIntegerField(default=10000)


class TaskModel(models.Model):
    status = models.CharField(max_length=1000)
    action = models.CharField(max_length=1000)
    bucket = models.ForeignKey(BucketModel)


class FileModel(models.Model):
    task=models.ForeignKey(TaskModel, default=None)
    file_path = models.CharField(max_length=1000)
    error = models.TextField(null=True)

web_rm/smart_rm/forms.py
from django import forms
from smart_rm import models

class AddBucketForm(forms.ModelForm):
    class Meta:
        model = models.BucketModel
        fields = ["name", "bucket_path", "max_size","time_files_storage","size_files_storage"]

web_rm/smart_rm/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
import os

from django.urls import reverse_lazy
from django.views.generic import FormView
from django.views.generic.edit import DeleteView

from smart.bucket import Bucket
from smart.remover import Remover
from smart.log import create_logger
from smart import smart_rm, smart_trash
from smart.file_utils import regular_expression_search

from models import BucketModel, TaskModel, FileModel

# Create your views here.
from smart_rm.forms import AddBucketForm


def select_files_for_removing_view(request, path):
    if path is None:
        path = os.path.expanduser("~")
    files =[]
    for file in os.listdir(path):
        file_path =  os.path.join(path,file)
        if os.path.islink(file_path):
            file_type = "link"
        elif os.path.isfile(file_path):
            file_type = "file"
        elif os.path.isdir(file_path):
            file_type = "directory"
        else:
            file_type = "unknown"

        read_ok = os.access(file_path, os.R_OK)

        files.append({"name": file, "path": file_path, "type": file_type,"read_ok": read_ok})

    directories = dir_paths_from_current_to_root(path)

    buckets = BucketModel.objects.values()

    return render(
        request=request,
        template_name='smart_rm/smart_remove.html',
        context={
            'files': files,
            'directories': directories,
            'buckets': buckets,
            'current_dir': path
        }
    )


def dir_paths_from_current_to_root(path):
    directories = []
    current_dir = os.path.abspath(path)
    dir_name =  os.path.basename(path)
    while len(dir_name):
        directories.append({"name": dir_name,"path": current_dir})
        current_dir = os.path.dirname(current_dir)
        dir_name = os.path.basename(current_dir)
    else:
        directories.append({"name": "/","path": "/"})
    directories.reverse()
    return directories


def remove_files(request):
    files = request.POST.getlist("added[]")
    bucket_id = request.POST.getlist("bucket_id")[0]
    force_flag = bool(request.POST.getlist("force"))
    recursive_flag = bool(request.POST.getlist("recursive"))
    directory_flag = bool(request.POST.getlist("dir"))
    regex = request.POST.getlist("regex")[0]
    regex_files = []
    if regex:
        for file in files:
            regex_files.extend(regular_expression_search(
                directory=file,
                regular_expression=regex))

        files = regex_files

    bucket = BucketModel.objects.get(id=bucket_id)
    remover = Remover(
        # dry_run=arguments.dry_run,
        # interactive=arguments.interactive,
        force=force_flag,
        dir_flag=directory_flag,
        recursive_flag=recursive_flag,
        bucket_path=bucket.bucket_path,
        bucket_info_path=bucket.info_path,
        bucket_files_path=bucket.files_path,
        history_path=bucket.history_path,
        max_bucket_size=bucket.max_size,
    )

    logger  = create_logger(
        history_path=bucket.history_path,
        dry_run=False,
    )

    exceptions = smart_rm.remove_files(
        remover=remover,
        files=files,
        logger=logger
    )[0]
    del(logger)


    task = save_task(
        action="Remove",
        bucket=bucket,
        files=files,
        exceptions=exceptions
    )

    return render(
        request=request,
        template_name='smart_rm/result_form.html',
        context={
            "task": task,
            "errors_count": len(exceptions),
            "files": FileModel.objects.filter(task_id=task.id)
        }
    )


class AddBucketView(FormView):
    form_class = AddBucketForm

    def get(self, request, *args, **kwargs):
        form = self.form_class(initial=self.initial)

        return render(
            request=request,
            template_name='smart_rm/add_bucket_form.html',
            context={'form': form}
        )

    def post(self, request, *args,**kwargs):
        form = self.form_class(data=request.POST)

        if not form.is_valid():
                return render(
                request=request,
                template_name='smart_rm/add_bucket_form.html',
                context={'form': form}
            )

        if os.path.isabs(form.cleaned_data["bucket_path"]):
            bucket_path = form.cleaned_data["bucket_path"]
        else:
            bucket_path = os.path.join(os.path.expanduser("~"), form.cleaned_data["bucket_path"])


        bucket = BucketModel(
            name=form.cleaned_data["name"],
            bucket_path=bucket_path,
            files_path=os.path.join(bucket_path,"files"),
            info_path=os.path.join(bucket_path,"info"),
            history_path=os.path.join(bucket_path,"history_path"),
            max_size=form.cleaned_data["max_size"],
            time_files_storage=form.cleaned_data["time_files_storage"],
            size_files_storage=form.cleaned_data["size_files_storage"],
        )
        bucket.save()

        task = save_task(
            action="Add bucket",
            bucket=bucket,
        )

        Bucket(
            bucket_path=bucket.bucket_path,
            bucket_files_path=bucket.files_path,
            bucket_info_path =bucket.info_path,
        ).prepare()

        return HttpResponseRedirect(reverse_lazy('smart_rm:view_buckets'))


def view_buckets(request):

    buckets = BucketModel.objects.values()
    return render(
        request=request,
        template_name='smart_rm/smart_bucket.html',
        context={'buckets':buckets}
    )

def view_bucket_contents(request, pk):
    bucket = BucketModel.objects.get(id=pk)
    contents = Bucket(
        bucket_path=bucket.bucket_path,
        bucket_info_path=bucket.info_path,
        bucket_files_path=bucket.files_path
    ).get_contents()
    return render(
        request=request,
        template_name='smart_rm/bucket_files.html',
        context={
            'bucket_contents': contents,
            'bucket_id': pk,
        }
    )


def restore_files(request):
    files=request.POST.getlist("added")
    bucket_id = request.POST.getlist("bucket_id")[0]
    bucket_model = BucketModel.objects.get(id=bucket_id)
    bucket = Bucket(
        bucket_path=bucket_model.bucket_path,
        bucket_info_path=bucket_model.info_path,
        bucket_files_path=bucket_model.files_path,
        history_path=bucket_model.history_path,
    )
    logger = create_logger(
        history_path=bucket_model.history_path,
        dry_run=False,
    )

    exceptions = smart_trash.restore_files(
        logger=logger,
        bucket=bucket,
        files=files
    )[0]

    task = save_task(
        action="Restore",
        bucket=bucket_model,
        files=files,
        exceptions=exceptions
    )

    return render(
        request=request,
        template_name='smart_rm/result_form.html',
        context={
            "task": task,
            "errors_count": len(exceptions),
            "files": FileModel.objects.filter(task_id=task.id)
        }
    )


class BucketDelete(DeleteView):
    model = BucketModel
    # task = save_task(
    #     bucket=model,
    #     action="Delete bucket"
    # )
    success_url = reverse_lazy('smart_rm:view_buckets')



def clean_bucket(request,pk):
    time_cleaning_flag = bool(request.POST.getlist("time_flag"))
    size_cleaning_flag = bool(request.POST.getlist("size_flag"))
    time = request.POST.get("time")
    size = request.POST.get("size")
    bucket_model = BucketModel.objects.get(id=pk)

    if time_cleaning_flag and len(time):
        time = int(time)
    else:
        time = bucket_model.time_files_storage

    if size_cleaning_flag and len(size):
        size = int(size)
    else:
        size = bucket_model.size_files_storage

    bucket = Bucket(
        bucket_path=bucket_model.bucket_path,
        bucket_files_path=bucket_model.files_path,
        bucket_info_path=bucket_model.info_path,
        size_files_storage=size,
        time_files_storage=time
    )

    actions=[]
    if time_cleaning_flag:
        bucket.clean_by_time()
        actions.append('time')

    if size_cleaning_flag:
        bucket.clean_by_size()
        actions.append('size')


    if not(size_cleaning_flag or time_cleaning_flag):
        bucket.clean()

    if len(actions) == 0:
        action_message = "Cleaned bucket"
    else:
        action_message = "Cleaned bucket (%s)" % ', '.join(actions)

    task = save_task(
        action=action_message,
        bucket=bucket_model,
    )

    return render(
        request=request,
        template_name='smart_rm/result_form.html',
        context={
            "task": task,
            "errors_count": 0,
            "files": FileModel.objects.filter(task_id=task.id)
        }
    )


def tasks_view(request, pk):
    bucket = BucketModel.objects.get(id=pk)
    tasks = TaskModel.objects.filter(bucket=bucket)

    return render(
        request=request,
        template_name="smart_rm/bucket_tasks.html",
        context={
            "tasks": tasks
        }
    )


def task_result_view(request, pk):

    task = TaskModel.objects.get(id=pk)
    files = FileModel.objects.filter(task_id=task.id)

    errors_count = 0
    for file in files:
        if file.error:
            errors_count+=1

    return render(
        request=request,
        template_name='smart_rm/result_form.html',
        context={
            "task": task,
            "errors_count": errors_count,
            "files": files
        }
    )


def save_task(
        action,
        bucket,
        files=None,
        exceptions=None,
):
    if exceptions:
        status="Errors"
    else:
        status="OK"

    task = TaskModel(
        action=action,
        status=status,
        bucket=bucket)

    task.save()

    if action == "Remove" or action == "Restore":

web_rm/smart_rm/templates/smart_rm/add_bucket_form.html
{% extends 'base.html' %}

{% block title %} New Bucket {% endblock %}

{% block content %}
    <form action="{% url "smart_rm:add_bucket"%}" method="post">
    {% csrf_token %}
{#        {{ form.as_p }}#}
        <div class="input-group add_bucket_form" >
          <span class="input-group-addon invert_button">Bucket Name</span>
          <input type="text" class="form-control add_bucket" placeholder="Name" name="{{ form.name.name }}" value="{{ form.name.value|default_if_none:"" }}" required>
{#            {{ form.name.name }}#}
        </div>
        <div class="input-group add_bucket_form" >
          <span class="input-group-addon invert_button">Bucket Path</span>
          <input type="text" class="form-control add_bucket" placeholder="Path" name="{{ form.bucket_path.name }}" value="{{ form.bucket_path.value|default_if_none:"" }}" required>
        </div>
        <div class="input-group add_bucket_form" >
          <span class="input-group-addon invert_button">Max Size</span>
          <input type="text" class="form-control add_bucket" placeholder="Size" name="{{ form.max_size.name }}" value="{{ form.max_size.value }}" required pattern="\d{0,100}">
        </div>
        <div class="input-group add_bucket_form">
            <span class="input-group-addon invert_button">Time for clean</span>
            <input type="text" class="form-control add_bucket" placeholder="Time for clean" name="{{ form.time_files_storage.name }}" value="{{ form.time_files_storage.value }}" pattern="\d{0,100}">
        </div>
        <div class="input-group add_bucket_form">
            <span class="input-group-addon invert_button">Size for clean</span>
            <input type="text" class="form-control add_bucket" placeholder="Size for clean" name="{{ form.size_files_storage.name }}" value="{{ form.size_files_storage.value }}" pattern="\d{0,100}">
        </div>
        {% if form.errors %}
        <div class="add_bucket_form">
            <div>Errors:</div>
            {{ form.errors }}
        </div>
        {% endif %}
        <div class="input-group add_bucket_form text-center">
            <input type="submit" value="Add Bucket" class="btn invert_button">
        </div>
    </form>
{% endblock %}

web_rm/smart_rm/templates/smart_rm/bucket_files.html
{% extends 'base.html' %}

{% block title %}Bucket Contents{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-lg-1">
            <a href="{% url "smart_rm:tasks" bucket_id %}" class="btn btn-default">Tasks</a>
        </div>
        <div class="col-lg-11">
            <form class="form-inline" action="{% url "smart_rm:clean_bucket" bucket_id%}" method="post">
                {% csrf_token %}
                <div class="input-group">
                    <span class="input-group-addon">
                        <input type="checkbox" name="time_flag" value="time_flag" id="time_checkbox">
                    </span>
                    <input id="time_input" disabled type="text" class="form-control" pattern="\d{0,15}" name="time" placeholder="time" style="width: 70px;">
                </div>
                <div class="input-group" >
                <span class="input-group-addon">
                    <input type="checkbox" name="size_flag" value="size_flag" id="size_checkbox">
                </span>
                <input id="size_input" disabled type="text" class="form-control" pattern="\d{0,15}" name="size" placeholder="size">
            </div>

                <button type="submit" class="btn btn-default" >Clean</button>
            </form>
        </div>
    </div>
    <div class="btn-toolbar form-inline">

        <div class="btn-group form-inline">

        </div>

    </div>



    {% if bucket_contents|length %}
    <form action="{% url "smart_rm:restore_files" %}" method="post">
        <input type="hidden" name="bucket_id" value="{{ bucket_id }}">
        {% csrf_token %}
        <table class="table table-panel table-hover">
            <colgroup>
                <col>
                <col>
                <col>
                <col>
                <col>
            </colgroup>
            <thead>
                <tr>
                    <th><input type="checkbox"  id="selall" value="1"  class="checkbox"></th>
                    <th>File</th>
                    <th>Real path</th>
                    <th>Deletion date</th>
                    <th>Size</th>
                </tr>
            </thead>
            {% for file in bucket_contents|dictsort:"NameInBucket" %}
                <tr>
                    <td> <input type="checkbox" class="checkbox check_add" name="added" value="{{ file.NameInBucket }}"></td>
                    <td> {{ file.NameInBucket }}</td>
                    <td> {{ file.Path }}</td>
                    <td> {{ file.DeletionDate }}</td>
                    <td> {{ file.Size }}</td>
                </tr>
            {% endfor %}
        </table>
        <div align="center">
            <input type="submit" value="Restore files" class="btn btn-default invert_button">
        </div>
    </form>
    {% else %}
        <div class="no_actions" align="center"> Empty bucket</div>
    {% endif %}

{% endblock %}

web_rm/smart_rm/templates/smart_rm/bucket_tasks.html
{% extends "base.html" %}

{% block title %} Tasks {% endblock %}

{% block content %}

    {% if tasks %}
        <h1>Tasks</h1>
        <table width="100%" class="table table-panel table-hover">
            <colgroup>
                <col width="33%">
                <col width="33%">
                <col>
            </colgroup>
            <thead>
                <tr>
                    <th>Action</th>
                    <th>Status</th>
                    <th>Files</th>
                </tr>
            </thead>
            {% for task in tasks %}
                <tr>
                    <th>
                        {{ task.action }}
                    </th>
                    <th>
                        {{ task.status }}
                    </th>
                    <th>
                        {% if task.action == "Remove" or task.action == "Restore"%}
                            <form action="{% url "smart_rm:task_result" task.id %}" method="post">
                            {% csrf_token %}
                                <button class="btn btn-default" type="submit">Files</button>
                            </form>
                        {% endif %}
                    </th>

                </tr>
            {% endfor %}
        </table>
    {% else %}
        <label>No Tasks</label>
    {% endif %}
{% endblock %}

web_rm/smart_rm/templates/smart_rm/bucketmodel_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Delete Bucket{% endblock %}
{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <div align="center" class="delete_bucket">
        <p>Are you sure you want to delete "{{ bucketmodel.name }}"?</p>
        <p>Path: {{ bucketmodel.bucket_path }}</p>
        <input type="submit" value="Confirm" class="btn btn-danger delete_confirm"/>
    </div>

</form>
{% endblock  %}

web_rm/smart_rm/templates/smart_rm/result_form.html
{% extends 'base.html' %}

{% block title %}Task result{% endblock %}

{% block content %}
    <h1>Task Result</h1>
    <br>

    {% if files|length > errors_count %}
         <h2>
             {% if task.action == "Remove" %}
                 Removed
             {% elif task.action == "Restore" %}
                 Restored
             {% endif %}
         </h2>

        {% for file in files %}
            {% if not file.error %}
                <p>{{ file.file_path }}</p>
            {% endif %}
        {% endfor %}
    {% endif %}
    {% if errors_count %}
        <h2>Errors</h2>
        <table class="table table-panel table-hover">
            <colgroup>
                <col width="50%">
                <col>
            </colgroup>
            <thead>
                <tr>
                    <th>File</th>
                    <th>Error</th>
                </tr>
            </thead>

            {% for file in files %}
                {% if file.error %}
                    <tr>
                        <td>{{ file.file_path }}</td>
                        <td>{{ file.error }}</td>
                    </tr>
                {% endif %}
            {% endfor %}
        </table>
    {% endif %}
    {% if task.action != "Remove" and task.action != "Restore" %}
        <label>{{ task.action }}</label>
    {% elif  not files|length  and not errors_count%}
        <label>No Tasks</label>
    {% endif %}

{% endblock content %}

web_rm/smart_rm/templates/smart_rm/smart_bucket.html
{% extends 'base.html' %}

{% block title %} Bucket {% endblock title %}

{% block content %}
    <table class="table table-panel table-hover">
        <colgroup>
            <col width="10%">
            <col>
            <col width="8%">
            <col width="8%">
            <col width="8%">

        </colgroup>
        <thead>
            <tr>
                <th>Name</th>
                <th>Path</th>
                <th class="text-nowrap">Clean by time</th>
                <th class="text-nowrap">Clean by size</th>
                <th class="text-nowrap">Delete Bucket</th>
            </tr>
        </thead>
        {% for bucket in buckets %}
            <tr>
                <td><a href="{% url "smart_rm:bucket_files" bucket.id %}">{{ bucket.name }}</a></td>
                <td>{{ bucket.bucket_path }}</td>
                <td>{{ bucket.time_files_storage }}</td>
                <td>{{ bucket.size_files_storage }}</td>
                <td>
                    <form action="{% url "smart_rm:del_bucket" bucket.id %} method='post' ">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger" >Delete</button>
                    </form>
                </td>
            </tr>
        {% endfor %}
    </table>
{% endblock content %}

web_rm/smart_rm/templates/smart_rm/smart_remove.html
{% extends 'base.html' %}

{% block title %} Bucket {% endblock title %}

{% block content %}
    {% for dir in directories %}
        <a class="path_link" href="{% url 'smart_rm:view_files' dir.path %}">
            {{ dir.name }} >
        </a>
    {% endfor %}
    <br>
    {% if files|length %}
    <form action="{% url "smart_rm:remove_files"%}" method="post">
    <input type="hidden" name="current_dir" value="{{ current_dir }}">
        {% csrf_token %}
        <div class="btn-group form-inline" style="width: 100%">
            <select name="bucket_id" class="form-control" class="remove_option">
                {% for bucket in buckets|dictsort:"name" %}
                    <option value="{{ bucket.id }}">{{ bucket.name }}</option>
                {% endfor %}
            </select>
            <input type="checkbox" name="recursive" value="true" id="recursive" class="remove_option"><label for="recursive">recursive</label>
            <input type="checkbox" name="dir" value="true" id="directories" class="remove_option"><label for="directories">directories</label>
            <input type="checkbox" name="force" value="force" id="force" class="remove_option"><label for="force" >force</label>
            <label class="remove_option">regex</label><input type="text" class="form-control" name="regex">
        </div>
        <table class="table" >
            <colgroup>
                <col>
                <col width="98%">
            </colgroup>
            <thead>
                <tr>
                    <th><input type="checkbox"  id="selall" value="1"  class="checkbox"></th>
                    <th>File</th>
                </tr>
            </thead>
            {% for file in files|dictsort:"name" %}
                <tr>
                    <td>
                        <input type="checkbox" class="checkbox check_add" name="added[]" value="{{ file.path }}">
                    </td>
                    <td>
                        {% if file.type == "directory"%}
                            {% if file.read_ok%}
                                <a href="{% url 'smart_rm:view_files' file.path %}">
                                    <div>
                                        <span class="glyphicon glyphicon-folder-open" aria-hidden="true"></span>
                                        {{ file.name }}
                                    </div>
                                </a>
                            {% else %}
                                <div>
                                    <span class="glyphicon glyphicon-folder-close" aria-hidden="true"></span>
                                    {{ file.name }}
                                </div>
                            {% endif %}
                        {% else %}
                        <div>
                            <span class="glyphicon glyphicon-file" aria-hidden="true"></span>
                            {{ file.name }}
                        </div>
                    {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </table>
        <div align="center">
            <input type="submit" value="Remove" class="btn invert_button" >
        </div>

    </form>
    {% else %}
        <div class="no_actions" align="center"> Empty directory</div>
    {% endif %}
{% endblock content %}